### ISSUE TITLE
Duplicated Requests

### ISSUE THREAD

**Issue by scerelli** [commercelayer/commercelayer-react-components#187]
**Describe the bug**
While selecting a payment method from the available payments the component in charge of selecting the payment method makes duplicated calls for each request. I didn't check if this behavior replicates also on other components but on the payment you can notice it quite easily.

This behavior has been noticed by inspecting the network requests in the [hosted checkout](https://github.com/commercelayer/commercelayer-react-checkout), but I'm opening the issue in this repository  because I implemented a checkout page myself, using this library and I experience the same issue.

**To Reproduce**
1. Navigate to an hosted checkout of any commerce
2. Go to the payment section
3. Switch between payment while checking network requests

**Expected behavior**
I expect the react components to do 1 single requests if needed

**Video Recording**
https://www.youtube.com/watch?v=LJNHDQ95x8k

**Desktop / Mobile:**
 - OS: Any
 - Browser Any
 - Version Any

**Comment by acasazza** [comment]
Hi @scerelli, I have already fixed that on this pull request #186 🙌🏻

**Comment by scerelli** [comment]
grande ale!
