### ISSUE TITLE
Unnecessary large bundle size

### ISSUE THREAD

**Issue by Xaptor** [commercelayer/commercelayer-react-components#250]
**Describe the bug**
I created a NextJS app with SSG and build a product page where I am using the components Commercelayer, OrderStorage, OrderContainer, ItemContainer as shown in the Add to cart sample of the readme section. This results in a bundle where AdyenPayment.js and a states.json + countries.json triggered from /lib/utils/countryStateCity.js is bundled. That functionality is not used but makes 50% of my bundle size. Is it a bug or something wrong on my side?

**To Reproduce**
1.) Create next app
2.) Build add to cart sample page
3.) Use webpack analyzer to show bundle content 

**Expected behavior**
AdyenPayment and states.json + countries.json are not included and therefore smaller bundle size.

**Screenshots**
![image](https://user-images.githubusercontent.com/7997506/182036838-8248cf20-253f-4a01-a3e1-dd801e0603f5.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 103.0.5060.134

**Additional context**
I am using version 3.14.1

**Comment by acasazza** [comment]
Hi @Xaptor ,

We're working on a tree-shaking version to avoid that, where you will only import the component you need.

The version should be `v4.0.0`.

You could try our alpha `v4.0.0-alpha.2`, you can import the `OrderContainer` directly by `@commercelayer/react-components/orders/OrderContainer` and so on.

Let me know 🙌🏻
