### ISSUE TITLE
QuantitySelector Component Does Not Work

### ISSUE THREAD

**Issue by osseonews** [commercelayer/commercelayer-react-components#281]
Adding the Quantity Selector component to an add to cart page does not work. No matter what you do, the quantity always just resets to the min value, and you can never add more than the min value to the cart. Our basic code is below. It works to add 1 of the SKU to the cart, but the quantity is always 1, no matter what. We have checked each SKU and they have the correct inventory, so it's not clear why the QuantitySelector always just resets to 1.  Also, what's strange is that the Add to Cart component cannot access the quantity from the QuantitySelector component? We can access the skuCode in the Add toCart, but not the quantity? And there is no prop to Add to Cart to add a specific quantity? This should be an Add to Cart prop or at least be exposed in some way from the Quantity Selector

Code:
------
```
<ItemContainer>
      <Price code={variant?.sku} className='text-xl' />
{/*selects the variant*/}        
<ProductOptions
          product={product}
          selectedOptions={selectedOptions}
          setSelectedOptions={setSelectedOptions}
        />
{/*this does nothing. qty always resets to 1 no matter what. We added a disabled prop b/c if you don't the component doesn't work at all - also we added the skuCode even if it should get it anyway from the top level component*/}        
<QuantitySelector skuCode={variant?.sku} disabled={false} min={1} max={3} />
<AddToCartButton
          skuCode={variant?.sku}
          className='mt-12 block h-14 w-full rounded-md bg-violet-400 px-6 font-semibold text-white disabled:bg-gray-300'
        />
</ItemContainer>

```

**Comment by acasazza** [comment]
Hi @osseonews, at the moment, there is no way to add the quantity directly to the `AddToCartButton`. I can add that anyway. The `QuantitySelector`  works with `VariantSelector`, if you are not using that in your `ProductOptions`, it is probably the issue. Here there is an example https://github.com/commercelayer/commercelayer-react-components/blob/master/pages/order.tsx

**Comment by acasazza** [comment]
Removed in the latest version `v4.0.0`
