### ISSUE TITLE
document all checkout related components

### ISSUE THREAD

**Issue by korsvanloon** [commercelayer/commercelayer-react-components#346]
I see there are many checkout related components (addresses, shipping methods, payment) available that have no documentation yet.

**Comment by acasazza** [comment]
Hi @korsvanloon . We're working on that. BTW, you can look at our hosted checkout that uses our components https://github.com/commercelayer/commercelayer-react-checkout.

**Comment by acasazza** [comment]
Hi @korsvanloon ! Here is the new documentation https://commercelayer.github.io/commercelayer-react-components 🙌🏻
