### ISSUE TITLE
Update the cart's line item by replacing the quantity rather than incrementing it

### ISSUE THREAD

**Issue by sajanbasnet75** [commercelayer/commercelayer-react-components#396]
### Is your feature request related to a problem? Please describe

Is there an option to substitute the existing quantity of an item in the cart with a new value when using the `<AddToCartButton> ` component? 

For example, if the current cart holds an item with a quantity of 3, can the new quantity of 5 replace the existing quantity rather than being added to it?

```<AddToCartButton quantity=5 skuCode={code}/>```

### Describe the solution you'd like

perhaps some additional params that gets sent to AddToCartButton? 

### Are you able to assist to bring the feature to reality?

no

**Comment by acasazza** [comment]
Hi @sajanbasnet75 . Well, it's not a conventional behavior in our API as you can read here https://docs.commercelayer.io/core/v/how-tos/placing-orders/shopping-cart/add-to-cart#additional-notes.
