### ISSUE TITLE
Improve `CustomerInput` validation when used for `customer_email`

### ISSUE THREAD

**Issue by malessani** [commercelayer/commercelayer-react-components#410]
### Is your feature request related to a problem? Please describe

At the moment accepted value for `customer_email` are:

- email@gmail.c with 1 char TLD
- email..@gmail.com with double dots 

### Describe the solution you'd like

It would be nice to have this check when a user is going to input the email

### Are you able to assist to bring the feature to reality?

no

**Comment by yplahotya** [comment]
`email@gmail..com` is also invalid.
