### ISSUE TITLE
Remove unnecessary imports

### ISSUE THREAD

**Issue by westhouseit** [commercelayer/commercelayer-react-components#55]
I noticed that when using the components Stripe code is always loaded whether or not it's being used. This leads to a larger bundle, more network requests, and extra JS parsing. Also, there's the Stripe tracking code being added with no obvious way to disable it.

Perhaps I missed something, but it would really help to extract as much as possible from the core components. How about having payment gateways as plugins or only loaded based on a config?

**Comment by acasazza** [comment]
Hi! Which version are you using?

**Comment by westhouseit** [comment]
2.28.0. I just noticed that 2.29.0 was just released, checking that now.

**Comment by westhouseit** [comment]
I can only see Paypal and OrderNumber as changes between releases.

**Comment by acasazza** [comment]
Hey @westhouseit, I've just fixed the issue. Thank you for your help. Really appreciate 🙌🏻

**Comment by westhouseit** [comment]
That's great, thanks!
