### ISSUE TITLE
JS SDK dependency

### ISSUE THREAD

**Issue by westhouseit** [commercelayer/commercelayer-react-components#75]
I notice that these components are set to a fixed 3.10.0 JS SDK dependency. Is there any particular reason the components won't work with a v4.x SDK? If so, can anything be done about this?

**Comment by acasazza** [comment]
Hi @westhouseit, there isn't any particular reason. We're working on a new version of the SDK without `active-resource` as a dependency. When it's ready, we will add it to our react components.
